In [ ]:
import numpy as np
array1 = np.array([1,2,3])
print('array type:',type(array1))
print('array1 array 형태:', array1.shape)

array2 = np.array([[1,2,3],[2,3,4]])
print('array2 type:',type(array2))
print('array2 array 형태:', array2.shape)

array3 = np.array([[1,2,3]])
print('array3 type:', type(array3))
print('array3 array 형태:', array3.shape)

array type: <class 'numpy.ndarray'>
array1 array 형태: (3,)
array2 type: <class 'numpy.ndarray'>
array2 array 형태: (2, 3)
array3 type: <class 'numpy.ndarray'>
array3 array 형태: (1, 3)


In [ ]:
list1=[1,2,3]
print(type(list1))
arrary1=np.array(list1)
print(type(array1))
print(array1,array1.dtype)

<class 'list'>
<class 'numpy.ndarray'>
[1 2 3] int64


In [ ]:
list2=[1,2,'test']
array2 = np.array(list2)
print(array2,array2.dtype)

list3=[1,2, 3.0]
array3 = np.array(list3)
print(array3,array3.dtype)

['1' '2' 'test'] <U21
[1. 2. 3.] float64


In [ ]:
array_int = np.array([1,2,3])
array_float=array_int.astype('float64')
print(array_float,array_float.dtype)

array_int1=array_float.astype('int32')
print(array_int1, array_int1.dtype)

array_float1=np.array([1.1, 2.1, 3.1])
array_int2=array_float1.astype('int32')
print(array_int2, array_int2.dtype)

[1. 2. 3.] float64
[1 2 3] int32
[1 2 3] int32


In [3]:
import numpy as np
array1 = np.arange(start=1, stop=10)
print('array1:',array1)
value = array1[2]
print('value:',value)
print(type(value))


array1: [1 2 3 4 5 6 7 8 9]
value: 3
<class 'numpy.int64'>


In [4]:
array1[0]=9
array1[8]=0
print('array1:', array1)

array1: [9 2 3 4 5 6 7 8 0]


In [5]:
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3,3)
print(array2d)

print('(row=0, col=0) index 가리키는 값:',array2d[0,0])
print('(row=0, col=1) index 가리키는 값:',array2d[0,1])
print('(row=1, col=0) index 가리키는 값:',array2d[1,0])
print('(row=2, col=2) index 가리키는 값:',array2d[2,2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(row=0, col=0) index 가리키는 값: 1
(row=0, col=1) index 가리키는 값: 2
(row=1, col=0) index 가리키는 값: 4
(row=2, col=2) index 가리키는 값: 9


In [7]:
array1= np.arange(start=1, stop=10)
array3 = array1[0:3]
print(array3)
print(type(array3))

[1 2 3]
<class 'numpy.ndarray'>


In [9]:
array1 = np.arange(start=1,stop=10)
array4 = array1[:3]
print(array4)

array5 = array1[3:]
print(array5)

array6 = array1[:]
print(array6)

[1 2 3]
[4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


In [ ]:
list2 = [1,2,'test']
array2 = np.array(list2)
print(array2, array2.dtype)
list3 = [1,2,3.0]
array3 = np.array(list3)
print(array3, array3.dtype)


In [1]:
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3,3)
array3 = array2d[[0,1],2]
print('array2d[0,1],2] => ',array3.tolist())

array4 = ('array2d[[0,1]], 0:2')
print('array2d[[0,1]], 0:2') =>', array4.tolist())

array5 =array2d[0,1]
print('array2d[[0,1]]') =>', array5.tolist())


SyntaxError: ignored

In [4]:
import numpy as np
array1d = np.arange(start=1, stop=10)
array3 = array1d[array1d>5]
print('array1d > 5 불린 인덱싱 결과 값:', array3)


array1d > 5 불린 인덱싱 결과 값: [6 7 8 9]


In [5]:
array1d >5

array([False, False, False, False, False,  True,  True,  True,  True])

In [ ]:
org_array = np.array ([3,1,9,5])
print('원본행렬:', org_array)
sort_array1= np.sot(org_array)
print('np.sort() 호출 후 반환된 정렬 행렬:'), sort_array

In [ ]:
import numpy as np
col_name=['col']
list 1=[1,2,3]
array1 = np.array(list1)
print('array1 shape:',array1.shape)

df_list1=pd.DataFrame(list1, columns= col_name1)
print('1차원 리스트로 만든 DataFrame:')

In [5]:
titanic_sorted = titanic_df.sort_values(by=['Name'])
titanic_sorted.head(3)


In [8]:
def get_category(age):
  cat=''
  if age <=5:cat = 'Baby'
  elif age <=12: cat = 'Child'
  elif age <=18: cat = 'Teenager'
  elif age <=25: cat = 'Student'
  elif age <=35: cat = 'Young Adult'
  elif age <= 60 : cat = 'Adult'
  else : cat = 'Elderly'

  return cat

import dataframe as df

titanic_df['Age_cat']=titanic_df['Age'].apply(lambda x : get_category(x))
titanic_df[['Age','Age_cat']].head()

ModuleNotFoundError: ignored